#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("E_Health.Resource", IsApplication=true)]

namespace E_Health
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int black = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash_screen = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int button1 = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int button4 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int button5 = 2131165201;
			
			// aapt resource value: 0x7f070001
			public const int editText1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int editText2 = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int editText3 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int editText4 = 2131165190;
			
			// aapt resource value: 0x7f07000f
			public const int myListView = 2131165199;
			
			// aapt resource value: 0x7f070009
			public const int radioButton1 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int radioButton2 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int radioButton3 = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int radioGroup1 = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int ratingBar1 = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int textView2 = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int textView3 = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int textView4 = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int textView5 = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Results = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
